### ISSUE TITLE
HACS Support

### ISSUE THREAD

**Issue by JeedHome44** [nqkdev/home-assistant-vacuum-styj02ym#1]
Hi,
I'm french! Sorry for my bad english.
HACS support is possible?
Thank you!

**Comment by zen** [comment]
Not no, but it's relatively easy to fix

**Comment by JeedHome44** [comment]
it's do! thank you so much! :)

**Comment by KrzysztofHajdamowicz** [comment]
I'll bump this one. Seems #4 fixes this, but merge conflicts needs to be resolved.

**Comment by HydrelioxGitHub** [comment]
Any news about the merge of your PR @KrzysztofHajdamowicz  ?

**Comment by KrzysztofHajdamowicz** [comment]
> Any news about the merge of your PR @KrzysztofHajdamowicz  ?

Unfortunately no, I have no write access to this repository. Feel free to use my forked one, it's HACS compatible.
