### ISSUE TITLE
Water speed

### ISSUE THREAD

**Issue by JeedHome44** [nqkdev/home-assistant-vacuum-styj02ym#2]
Hi,

Is it possible to add the possibility of controlling the speed of water flow when you put a water tank in the robot?
There are 3 speeds in the Mi Home app

thank you so much

**Comment by JeedHome44** [comment]
can someone say me if it's possible to add speed water?

**Comment by kovbalazs89** [comment]
Hi JeedHome44,
Yes, ther is a parameter of the vacuum's attributes: water_grade

The parameter values are:
Low = 11
Medium = 12
High = 13

You can set these, with the vacuum.send_command service in home assistant.

Example to set the water level to high:
entity_id: vacuum.mi_vacuum_mop_p
command: set_suction
params: 13

**Comment by JeedHome44** [comment]
hi,

Thank you very much!

I need to do 3 script in Hassio.

1 for low, 1 for medium and 1 for high.

I don't have set_suction command in my Hassio.
Where do you find it?

**Comment by JeedHome44** [comment]
Where do you see set_suction in vaccum.py file?

**Comment by kovbalazs89** [comment]
Hi,

this is an axemple from my scripts.yaml:

'1586105694782':
  alias: Water Level
  sequence:
  - data:
      command: set_suction
      params: 13
    entity_id: vacuum.mi_vacuum_mop_p
    service: vacuum.send_command

**Comment by JeedHome44** [comment]
ok thank you i do the same and it's work! Great! :)

**Comment by sheminasalam** [comment]
@JeedHome44 @kovbalazs89  How are you able to change the mode from vacuuming to mopping and combined vacuuming and mopping? I cant find any code to make that change

**Comment by JeedHome44** [comment]
We can't change the mode.  it changes depending on the type of tank that is put in!
