### ISSUE TITLE
StateVacuumDevice is deprecated, modify MiroboVacuum2 to extend StateVacuumEntity

### ISSUE THREAD

**Issue by X1pheR** [nqkdev/home-assistant-vacuum-styj02ym#23]
I just noticed that master was updated with #15 but after updating and restarting I am getting the below error in de log. I'm on HA version 0.115.4. As a sidenote will the other open PR's also get merged as they bring additional functionality?

Logger: homeassistant.components.vacuum
Source: components/vacuum/__init__.py:390
Integration: Stofzuigen (documentation, issues)
First occurred: 1:12:18 (1 occurrences)
Last logged: 1:12:18

StateVacuumDevice is deprecated, modify MiroboVacuum2 to extend StateVacuumEntity

**Comment by Gawronnek** [comment]
HA 115.4

Logger: homeassistant.components.vacuum
Source: components/vacuum/__init__.py:390
Integration: Odkurzacz (documentation, issues)
First occurred: 19:40:36 (1 occurrences)
Last logged: 19:40:36

StateVacuumDevice is deprecated, modify MiroboVacuum2 to extend StateVacuumEntity

**Comment by snp88** [comment]
the same issuer on 0.117

**Comment by johination** [comment]
I have the same with 117.1 Update!

**Comment by KrzysztofHajdamowicz** [comment]
Seems like solved by 9d5dfa2fe6db21ccdb9ea149c208d72ccd89a4e6
