### ISSUE TITLE
Clean Segment with Send Command

### ISSUE THREAD

**Issue by Albertox0404** [nqkdev/home-assistant-vacuum-styj02ym#32]
Hi, i am trying to send the command "app_segment_clean" using the "send_command" service on the Xiaomi STYJ02YM, to clean a specific room, but with no success. Someone knows how to do that on Home Assistant or directly with miio2 on the command line?
![image](https://user-images.githubusercontent.com/8124142/110225194-4083fd80-7ee3-11eb-8e6f-efbc64cbddac.png)

Thank you very much :)

**Comment by JiriFurda** [comment]
Hi, I don't have one yet so it is only a blind guess. But it looks like you can use command [set_mode_withroom](https://github.com/SnDsound/STYJ02YM/blob/d85f0049bee0c22e3e46e0ba623df9c3800d4ac6/Integracja%20STYJ02YM%20i%20STYTJ02YM.txt#L269)

**Comment by Albertox0404** [comment]
wow, it works !!!!!

Thank u so so much from Spain :)
