### ISSUE TITLE
Error after updating to 2021.06.0

### ISSUE THREAD

**Issue by Jaguaza** [nqkdev/home-assistant-vacuum-styj02ym#40]
My vacuum cleaner disappears from my Home Assistant and I only get the following error.

Logger: homeassistant.config
Source: config.py:849
First occurred: 0:40:06 (1 occurrences)
Last logged: 0:40:06

Platform error: vacuum - Integration 'miio2' not found.

**Comment by provaprova1** [comment]
Same to me

**Comment by Jaguaza** [comment]
> Same to me

Make the change that this user proposes and it will work.

https://github.com/nqkdev/home-assistant-vacuum-styj02ym/pull/36/commits/276fa3db3bf7de8960a04bf0c3bcdf29487ed15b

**Comment by xFastz** [comment]
thanks! works now.

**Comment by beped** [comment]
This project its not been updated anymore? Someone should just take it and keep updating.

**Comment by dogmatic69** [comment]
Can you close this issue as it is resolved
