### ISSUE TITLE
Don't work with new release 2022.3.0

### ISSUE THREAD

**Issue by febo7011** [nqkdev/home-assistant-vacuum-styj02ym#55]
I have the Vacuum robot styj02ym.
Before this new release worked very well miio2.

Today installed 2022.3.0 and the integration don't work.
Also when i check my configuration this is the error shown.
Platform error vacuum.miio2 - Requirements for miio2 not found: ['python-miio==0.5.3'].

How can i solve this problem?

**Comment by maymaymay** [comment]
Same here.

**Comment by febo7011** [comment]
Yesterday I searched for a solution myself.

I found the file with the setting python-miio==0.5.3.
In the path config/custom_component/ there is the file manifest.json.
I substituted the present requirement with this new one.
   "requirements": [
    "construct==2.10.56",
    "python-miio==0.5.9"
]
probably python-miio 0.5.3 was missed in the release change and now is present 0.5.9.

In my case, the object robot is created and it seems restored.
I'm not sure that all services work well like before.
At the weekend I will do some tests to understand if all works.

Regards

**Comment by maymaymay** [comment]
My manifest looks like this:
```
{
    "domain": "miio2",
    "name": "Xiaomi miio vacuum STYJ02YM",
    "version": "1.0.0",
    "documentation": "",
    "requirements": [
        "construct==2.10.56",
        "python-miio==0.5.6"
    ],
    "dependencies": [],
    "codeowners": []
}
```
sionce 03.08.2021.

**Comment by Raddii** [comment]
I had the same problem too. For me, your hint also worked. Thanks @febo7011

**Comment by maymaymay** [comment]
In my case it was:
`"python-miio==0.5.6"`
Czange to:
`"python-miio==0.5.9"`
helped.

**Comment by salvadornico** [comment]
2022.3.3 introduces another breaking change, this time due to deprecated classes. I've updated pull request #56 to reflect this. It's tested and working on my installation.

**Comment by tnrclkr** [comment]
changing to 0.5.10 fixed here. Thank u guys

**Comment by agustusbotti** [comment]
> 2022.3.3 introduces another breaking change, this time due to deprecated classes. I've updated pull request #56 to reflect this. It's tested and working on my installation.

I made the changes @salvadornico  commented but when I go to restart HomeAssistant it gives me this error

> Platform error vacuum.miio2 - Requirements for miio2 not found: ['python-miio==0.5.6'].

I am not able to solve this. Could you help me?

**Comment by febo7011** [comment]
> > 2022.3.3 introduces another breaking change, this time due to deprecated classes. I've updated pull request #56 to reflect this. It's tested and working on my installation.
> 
> I made the changes @salvadornico commented but when I go to restart HomeAssistant it gives me this error
> 
> > Platform error vacuum.miio2 - Requirements for miio2 not found: ['python-miio==0.5.6'].
> 
> I am not able to solve this. Could you help me?

If you have installed the release 2022.3.3 you have to change from python-miio==0.5.6 to python-miio==0.5.10.

This setting is inside of the file config/custom_component/miio2/manifest.json

**Comment by maymaymay** [comment]
Chang it i manifest file to 5.11

Pozdrawiam,

Marek Majka
tel.: 501 488 559

czw., 10 mar 2022, 12:30 użytkownik agustusbotti ***@***.***>
napisał:

**Comment by KrzysztofHajdamowicz** [comment]
This repository looks pretty abandoned. Try this component: https://github.com/KrzysztofHajdamowicz/home-assistant-vacuum-styj02ym
I am also updating it rarely (as I am not a python developer and I have just enough skills to duct-tape it), but at least it works in 2022.3.x

**Comment by agustusbotti** [comment]
> > > 2022.3.3 introduces another breaking change, this time due to deprecated classes. I've updated pull request #56 to reflect this. It's tested and working on my installation.
> > 
> > 
> > I made the changes @salvadornico commented but when I go to restart HomeAssistant it gives me this error
> > > Platform error vacuum.miio2 - Requirements for miio2 not found: ['python-miio==0.5.6'].
> > 
> > 
> > I am not able to solve this. Could you help me?
> 
> If you have installed the release 2022.3.3 you have to change from python-miio==0.5.6 to python-miio==0.5.10.
> 
> This setting is inside of the file config/custom_component/miio2/manifest.json

Well, something was wrong with the installation of 2022.3.3, I deactivated miio2 restarted HAAS and then activated it again and it worked perfectly.
Thanks for the help

**Comment by antstyl** [comment]
> This repository looks pretty abandoned. Try this component: https://github.com/KrzysztofHajdamowicz/home-assistant-vacuum-styj02ym I am also updating it rarely (as I am not a python developer and I have just enough skills to duct-tape it), but at least it works in 2022.3.x

Cannot find it in HACS!
There is only one for Viomi

**Comment by KrzysztofHajdamowicz** [comment]
> > This repository looks pretty abandoned. Try this component: https://github.com/KrzysztofHajdamowicz/home-assistant-vacuum-styj02ym I am also updating it rarely (as I am not a python developer and I have just enough skills to duct-tape it), but at least it works in 2022.3.x
> 
> @KrzysztofHajdamowicz Cannot find it in HACS!
> There is only one for Viomi 

You have to manually add custom repository to HACS

**Comment by antstyl** [comment]
Thanks. its ok

**Comment by tnrclkr** [comment]
2022.4.0 same again...

**Comment by MartijnC1984** [comment]
> This repository looks pretty abandoned. Try this component: https://github.com/KrzysztofHajdamowicz/home-assistant-vacuum-styj02ym I am also updating it rarely (as I am not a python developer and I have just enough skills to duct-tape it), but at least it works in 2022.3.x

Thanks very much for keeping up this repository. Untill now I have managed to keep the original custom component alive manually by updating the python-miio every now and then; but having integration through HACS and your updates are a lot more convenient. 

Happy! Thank you!

**Comment by drorya1** [comment]
Stopped working on 2022.5.4 
Anyone found a solution ?

**Comment by Su4oNoK** [comment]
I'm edit "\config\custom_components\miio2\manifest.json"
    "python-miio==0.5.12"
```
{
  "domain": "miio2",
  "name": "Xiaomi miio vacuum STYJ02YM",
  "version": "2022.3.3",
  "documentation": "https://github.com/KrzysztofHajdamowicz/home-assistant-vacuum-styj02ym",
  "requirements": [
    "construct==2.10.56",
    "python-miio==0.5.12"
  ],
  "dependencies": [],
  "codeowners": ["@nqkdev", "@KrzysztofHajdamowicz"],
  "config_flow": false,
  "iot_class": "local_polling"
}
```
